import express from "express";
import helloRouter from "./hello.route.js";
import authRouter from "./auth.routes.js";
import vendorsRouter from "./vendor.routes.js";
import vendorAvailablityRouter from "./vendorAvailability.routes.js";
import reviewRoutes from "./review.routes.js";
import uploadRoutes from "./upload.routes.js";
import affiliateRoutes from "./affiliate.routes.js";
import categoriesRoutes from "./category.routes.js";
import productServicesRoutes from "./productService.routes.js";
import bannerRoutes from "./banner.routes.js";
import bookingRouter from "./booking.routes.js";
import ordersRouter from "./order.routes.js";
import franchiseRoutes from "./Franchise.routes.js";
import analyticsRouter from "./analytics.routes.js";
import transactionRouter from "./transaction.routes.js";
import userRouter from "./user.routes.js";
import memberRouter from "./member.routes.js";
import rewardRouter from "./reward.route.js";
import franchisheMilestoneRouter from "./franchise.milestone.routes.js";
import cashbackMilestoneRouter from "./cashback.milestone.routes.js";
import membershipMilestoneRouter from "./membership.milestone.routes.js";
import walletRoutes from "./wallet.routes.js";
import referralRouter from "./referral.routes.js";
import razorpayRouter from "./razorpay.routes.js";
import checkoutRouter from "./checkout.route.js";
import emiRouter from "./emi.routes.js";
import salesRepRouter from "./salesRep.routes.js";
import ticketRouter from "./ticket.routes.js";
import couponCodeRouter from "./couponCode.routes.js";
import cahsFreeRouter from "./cashfree.routes.js";
import adminVendorRouter from "./adminVendor.routes.js";
import membershipPackagesRouter from "./membershipPackages.routes.js";
import locationRouter from "./location.routes.js";

const router = express.Router();

// Mount the routers
router.use("/hello", helloRouter);
router.use("/auth", authRouter);
router.use("/vendors", vendorsRouter);
router.use("/vendor-availability", vendorAvailablityRouter);
router.use("/reviews", reviewRoutes);
router.use("/uploadFiles", uploadRoutes);
router.use("/categories", categoriesRoutes);
router.use("/product-services", productServicesRoutes);
router.use("/banners", bannerRoutes);
router.use("/bookings", bookingRouter);
router.use("/orders", ordersRouter);
router.use("/franchises", franchiseRoutes);
router.use("/analytics", analyticsRouter);
router.use("/transactions", transactionRouter);
router.use("/users", userRouter);
router.use("/membership", memberRouter);
router.use("/reward", rewardRouter);
router.use("/franchise-milestone", franchisheMilestoneRouter);
router.use("/cashback-milestone", cashbackMilestoneRouter);
router.use("/membership-milestones", membershipMilestoneRouter);
router.use("/wallet", walletRoutes);
router.use("/referral", referralRouter);
router.use("/razorpay", razorpayRouter);
router.use("/checkout", checkoutRouter);
router.use("/emi", emiRouter);
router.use("/cashfree", cahsFreeRouter);
router.use("/sales-rep", salesRepRouter);
router.use("/ticket", ticketRouter);
router.use("/admin-vendor", adminVendorRouter);
router.use("/coupon-code", couponCodeRouter);
router.use("/membership-packages", membershipPackagesRouter);
router.use("/location", locationRouter);
router.use("/affiliate", affiliateRoutes);

export default router;
